name: ylham_motors
description: "Ylham Motors commerce app"
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:

  app_ui:
    path: ./packages/app_ui

  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  data_provider:
    path: ./packages/data_provider
  equatable: ^2.0.5
#  firebase_messaging: ^14.7.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
#  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  package_info_plus: ^8.1.2
  path_provider: ^2.1.1
  persistent_storage:
    path: ./packages/storage/persistent_storage
  secure_storage:
    path: ./packages/storage/secure_storage
  shared_preferences: ^2.2.0
  storage:
    path: ./packages/storage/storage
  flutter_screenutil: ^5.9.0
  form_inputs:
    path: ./packages/form_inputs
  cached_network_image: ^3.3.0
  phosphor_flutter: ^2.0.1
  shimmer: ^3.0.0
  flutter_hooks: ^0.20.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  turkmen_localization_support: ^0.0.8
  carousel_slider: ^5.0.0
  flutter_widget_from_html: ^0.16.0
  
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

dependency_overrides:
  intl: ^0.18.1

flutter:
  generate: true
  uses-material-design: true