name: ylham_motors
description: "Ylham Motors commerce app"
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:

  app_ui:
    path: ./packages/app_ui

  bloc: ^9.2.0
  cupertino_icons: ^1.0.8
  data_provider:
    path: ./packages/data_provider
  equatable: ^2.0.7
  firebase_messaging: ^16.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.0
  hydrated_bloc: ^10.1.1
  intl: ^0.19.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  persistent_storage:
    path: ./packages/storage/persistent_storage
  secure_storage:
    path: ./packages/storage/secure_storage
  shared_preferences: ^2.3.4
  storage:
    path: ./packages/storage/storage
  flutter_screenutil: ^5.9.3
  form_inputs:
    path: ./packages/form_inputs
  cached_network_image: ^3.4.1
  phosphor_flutter: ^2.1.0
  shimmer: ^3.0.0
  flutter_hooks: ^0.21.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  turkmen_localization_support: ^0.0.8
  carousel_slider: ^5.0.0
  rxdart: ^0.28.0
  
dev_dependencies:
  build_runner: ^2.4.14
  envied_generator: ^1.3.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

dependency_overrides:
  intl: ^0.19.0

flutter:
  generate: true
  uses-material-design: true