name: data_provider
description: A package which handle 3rd layer data from out.
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.7
  hive: ^2.2.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
